language: node_js
node_js:
  - stable
  - lts/*
matrix:
  fast_finish: true
cache:
  directories:
    - node_modules
git:
  depth: 1
  submodules: false
install:
  - npm ci
before_script:
  - npm run lint
  - npm run build
script:
  - npm run test
