language: node_js
node_js:
  - stable
  - lts/*
matrix:
  fast_finish: true
cache:
  directories:
    - node_modules
git:
  depth: 1
  submodules: false
install:
  # Install bats
  - sudo add-apt-repository -y ppa:duggan/bats
  - sudo apt-get update
  - sudo apt-get install -y bats
  # Install Node Packages
  - npm ci
before_script:
  # check bash
  - type bash
  - bash --version
  # check npm
  - type npm
  - npm --version
  # check npx
  - type npx
  - npx --version
  # check code style
  - ./cmd/code.sh lint
  # build
  - ./cmd/code.sh build
script:
  - ./cmd/code.sh test
