version: '3.8'
services:
  base:
    build:
      context: '.'
      dockerfile: './docker/Dockerfile'
    image: 'base-cdk-bootstrap:latest'
  shared: &shared
    image: 'base-cdk-bootstrap:latest'
    stdin_open: true
    tty: true
  cdk:
    <<: *shared
    entrypoint: 'npx cdk'
    volumes:
      - '~/.aws:/root/.aws'
      - '.:/var/project'
  npm:
    <<: *shared
    entrypoint: 'npm'
    volumes:
      - '.:/var/project'
  npx:
    <<: *shared
    entrypoint: 'npx'
    volumes:
      - '.:/var/project'
