version: '3.8'
services:
  base:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: base-cdk-experiment:latest
  shared: &shared
    image: base-cdk-experiment:latest
    stdin_open: true
    tty: true
    volumes:
      - '.:/var/project:delegated'
      - 'log:/var/log/docker:delegated'
  bash:
    <<: *shared
    entrypoint: bash -c
  cdk:
    <<: *shared
    entrypoint: npx cdk
    volumes:
      - '~/.aws:/root/.aws'
      - '.:/var/project'
      - 'log:/var/log/docker:delegated'
  npm:
    <<: *shared
    entrypoint: npm
  npx:
    <<: *shared
    entrypoint: npx
volumes:
  log:
    driver: local

# References:
# - Performance tuning for volume mounts (shared filesystems)
#   https://docs.docker.com/docker-for-mac/osxfs-caching
